# Generated by Django 4.0 on 2023-05-17 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VentaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_merma', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_costo_producto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('importe_precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta_producto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('importe_precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.local')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='precioventa',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('producto',), name='unique_active_price'),
        ),
    ]
