# Generated by Django 4.0 on 2023-05-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadiaria',
            name='cantidad_venta',
            field=models.IntegerField(default=0),
        ),
    ]
