# Generated by Django 4.0 on 2023-05-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_ventadiaria_cantidad_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadiaria',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
