# Generated by Django 4.2.1 on 2023-05-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_gastosdiario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosdiario',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
