# Generated by Django 4.0 on 2023-05-19 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_ventadiaria_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventadiaria',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterField(
            model_name='precioventa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ventadiaria',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 5, 19, 9, 33, 51, 957191, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('salario_basico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.local')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_devengado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('total_nomina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.local')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.trabajador')),
            ],
            options={
                'unique_together': {('trabajador', 'fecha')},
            },
        ),
    ]
