# Generated by Django 4.0 on 2023-05-19 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_ventadiaria_options_alter_precioventa_activo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ventadiaria',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 5, 19, 10, 24, 48, 19110, tzinfo=utc)),
        ),
    ]
