# Generated by Django 4.0 on 2023-05-19 23:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_asistencia_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 5, 19, 23, 23, 56, 149714, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ventadiaria',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 5, 19, 23, 23, 56, 150713, tzinfo=utc)),
        ),
    ]
